stages:
  - test
  - build
  - scan
  - sign

include:
  - project: doca/gitlab-ci-lib
    file: container/build.yaml
  - project: doca/gitlab-ci-lib
    file: container/sign.yaml
  - project: doca/gitlab-ci-lib
    file: container/test.yaml

lint-dockerfile:
  extends: .tpl:container:test:hadolint

docker-build:
  extends: .tpl:container:build:kaniko
  needs:
    - lint-dockerfile

container_scanning:
  extends: .tpl:container:test:cve
  needs:
    - docker-build

sign:
  extends: .tpl:container:sign:sign-image
  needs:
    - docker-build

attest:
  extends: .tpl:container:sign:attest-image
  needs:
    - docker-build
